#  sort values

In [1]:
import pandas as pd
df=pd.DataFrame({'Name':['Alice','Bob','Charlie','David'],'Score':[88,92,86,90]})
df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     86
3    David     90

In [2]:
sorted_df=df.sort_values(by='Score',ascending=False)
sorted_df

      Name  Score
1      Bob     92
3    David     90
0    Alice     88
2  Charlie     86

In [3]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     86
1      Bob     92
0    Alice     88

In [4]:
df.set_index('Name',inplace=True)

In [5]:
df

         Score
Name
Alice       88
Bob         92
Charlie     86
David       90

# apply()

In [6]:
import pandas as pd
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return 'pass' if x>=50 else 'fail'
result=s.apply(pass_fail)
result

0    fail
1    pass
2    pass
3    fail
dtype: object

In [7]:
df=pd.DataFrame({"physics":[60,70,80],"chemistry":[65,75,85],"maths":[70,80,90]})
result1=df.apply(sum,axis=1) 
print(result1)

0    195
1    225
2    255
dtype: int64

In [8]:
result2=df.apply(sum,axis=0)
print(result2)

physics      210
chemistry    225
maths        240
dtype: int64

In [9]:
result3=df.apply(lambda x:x.mean())
print(result3)

physics      70.0
chemistry    75.0
maths        80.0
dtype: float64

In [10]:
df['Total']=df.apply(lambda x:x.sum(),axis=1)
df

   physics  chemistry  maths  Total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [14]:
def grade(Total):
    if Total>=250:
        return "A"
    elif Total>=200:
        return "B"
    else:
        return "C"

In [17]:
df["Grade"]=df["Total"].apply(grade)
df

   physics  chemistry  maths  Total Grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

In [18]:
import pandas as pd
df=pd.DataFrame({"Width":[1,2],"Height":[3,4]})
def get_stats(row):
    return [row['Width']*row['Height'],2*(row['Width']+row['Height'])]
df

   Width  Height
0      1       3
1      2       4

In [19]:
df.apply(get_stats,axis=1,result_type='expand')

   0   1
0  3   8
1  8  12

In [20]:
df.apply(get_stats,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [21]:
df.apply(get_stats,axis=1,result_type='broadcast')

   Width  Height
0      3       8
1      8      12

In [22]:
import pandas as pd
def add_value(x,y,z):
    return x+y+z
df=pd.DataFrame({'A':[1,2],'B':[10,20]})

In [25]:
df1=df.apply(add_value,args=(1,2))
print(df1)

   A   B
0  4  13
1  5  23

In [29]:
def add_value(x,m):
    return x*m
df1=df.apply(add_value,m=10)
print(df1)

    A    B
0  10  100
1  20  200

In [6]:
import pandas as pd
df=pd.DataFrame({"A":["1","2","3"],"B":["4","5","6"]})
print(df.dtypes)
df["A"]=df["A"].astype(int)
print()
print(df.dtypes)

A    object
B    object
dtype: object

A     int32
B    object
dtype: object

#  replace

In [7]:
df=pd.DataFrame({"Marks":[80,85,0,90],"Attendance":[75,80,0,85],"Grade":["A","B","F","A"]})
result=df.replace(0,60)
print(result)

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [8]:
result=df.replace([80,75],[90,80])
print(result)

   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A