In [1]:
import pandas as pd

In [2]:
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print()
print(type(myvar))
print()
print(myvar[0])

0    1
1    7
2    2
dtype: int64

<class 'pandas.core.series.Series'>

1

In [3]:
a=[1,7,2]
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print()
print(type(myvar))
print()
print(myvar[0])
print(myvar['y'])

x    1
y    7
z    2
dtype: int64

<class 'pandas.core.series.Series'>

1
7

In [4]:
a=(1.5,2,3,4,5)
myvar=pd.Series(a)
print(myvar)

0    1.5
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [5]:
student_name=['ram','shyam','radhe','seeta','geeta']
marks=[50,60,70,80,90]
myvar=pd.Series(marks,index=student_name,name='student result')
print(myvar)

ram      50
shyam    60
radhe    70
seeta    80
geeta    90
Name: student result, dtype: int64

#  subs CSV  :

In [6]:
import pandas as pd
subs=pd.read_csv('subs.csv',squeeze=True)  # squeeze : converts dataframe to series
print(subs)
type(subs)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

pandas.core.series.Series

In [7]:
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [8]:
subs.min()

33

In [9]:
subs.median()

123.0

In [10]:
subs.max()

396

In [11]:
subs[subs>200].size

59

In [12]:
subs[subs==subs.max()].index

Int64Index([330], dtype='int64')

# bollywood CSV :

In [13]:
import pandas as pd
b=pd.read_csv('bollywood.csv')
print(type(b))
b

<class 'pandas.core.frame.DataFrame'>

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [14]:
movies=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [15]:
type(movies)

pandas.core.series.Series

In [16]:
movies.head()  # bydefault first 5 display

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [17]:
movies.head(10) # how many display

movie
Uri: The Surgical Strike                       Vicky Kaushal
Battalion 609                                    Vicky Ahuja
The Accidental Prime Minister (film)             Anupam Kher
Why Cheat India                                Emraan Hashmi
Evening Shadows                             Mona Ambegaonkar
Soni (film)                             Geetika Vidya Ohlyan
Fraud Saiyaan                                   Arshad Warsi
Bombairiya                                      Radhika Apte
Manikarnika: The Queen of Jhansi              Kangana Ranaut
Thackeray (film)                         Nawazuddin Siddiqui
Name: lead, dtype: object

In [18]:
movies.tail() # # bydefault last 5 display

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [19]:
movies.tail(10) #  last 10 display

movie
Raaz (2002 film)                    Dino Morea
Zameen (2003 film)                  Ajay Devgn
Waisa Bhi Hota Hai Part II        Arshad Warsi
Devdas (2002 Hindi film)        Shah Rukh Khan
Kaante                        Amitabh Bachchan
Hum Tumhare Hain Sanam          Shah Rukh Khan
Aankhen (2002 film)           Amitabh Bachchan
Saathiya (film)                   Vivek Oberoi
Company (film)                      Ajay Devgn
Awara Paagal Deewana              Akshay Kumar
Name: lead, dtype: object

In [20]:
movies[0]

'Vicky Kaushal'

In [21]:
movies[-5:] # last 5

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [22]:
movies[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [23]:
movies[[0,1,3,4,8]]

movie
Uri: The Surgical Strike               Vicky Kaushal
Battalion 609                            Vicky Ahuja
Why Cheat India                        Emraan Hashmi
Evening Shadows                     Mona Ambegaonkar
Manikarnika: The Queen of Jhansi      Kangana Ranaut
Name: lead, dtype: object

In [24]:
'2 states (2014 film)' in movies

False

In [25]:
'Alia Bhatt' in movies.values

True

In [26]:
movies.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [27]:
movies.values

array(['Vicky Kaushal', 'Vicky Ahuja', 'Anupam Kher', ..., 'Vivek Oberoi',
       'Ajay Devgn', 'Akshay Kumar'], dtype=object)

In [28]:
movies.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Aahana Kumra         1
Gavie Chahal         1
Akanksha             1
Dia Mirza            1
Sumit Arora          1
Name: lead, Length: 566, dtype: int64

In [29]:
movies.value_counts(ascending=True)

Sumit Arora          1
Dia Mirza            1
Akanksha             1
Gavie Chahal         1
Aahana Kumra         1
                    ..
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, Length: 566, dtype: int64

In [30]:
x=movies.value_counts()
x[x>20]

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [31]:
y=movies.value_counts()
y["Akshay Kumar"]

48

In [32]:
z=movies[movies.values=='Akshay Kumar']
print(f"Total counts : {z.size}")
print(z)

Total counts : 48
movie
Kesari (film)                           Akshay Kumar
Mission Mangal                          Akshay Kumar
Housefull 4                             Akshay Kumar
Good Newwz                              Akshay Kumar
Gold (2018 film)                        Akshay Kumar
Toilet: Ek Prem Katha                   Akshay Kumar
Airlift (film)                          Akshay Kumar
Baby (2015 Hindi film)                  Akshay Kumar
Singh Is Bliing                         Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Brothers (2015 film)                    Akshay Kumar
Holiday: A Soldier Is Never Off Duty    Akshay Kumar
Entertainment (2014 film)               Akshay Kumar
The Shaukeens                           Akshay Kumar
Special 26                              Akshay Kumar
Once Upon ay Time in Mumbai Dobaara!    Akshay Kumar
Boss (2013 Hindi film)                  Akshay Kumar
Joker (2012 film)                       Akshay Kumar
Housefull 2                             Akshay Kumar
Thank You (2011 film)                   Akshay Kumar
Desi Boyz                               Akshay Kumar
Housefull (2010 film)                   Akshay Kumar
Khatta Meetha (2010 film)               Akshay Kumar
Tees Maar Khan (2010 film)              Akshay Kumar
Action Replayy                          Akshay Kumar
Blue (2009 film)                        Akshay Kumar
De Dana Dan                             Akshay Kumar
Singh Is Kinng                          Akshay Kumar
Tashan (film)                           Akshay Kumar
Bhool Bhulaiyaa                         Akshay Kumar
Namastey London                         Akshay Kumar
Welcome (2007 film)                     Akshay Kumar
Bhagam Bhag                             Akshay Kumar
Humko Deewana Kar Gaye                  Akshay Kumar
Phir Hera Pheri                         Akshay Kumar
Mere Jeevan Saathi (2006 film)          Akshay Kumar
Deewane Huye Paagal                     Akshay Kumar
Dosti: Friends Forever                  Akshay Kumar
Garam Masala (2005 film)                Akshay Kumar
Insan                                   Akshay Kumar
Aitraaz                                 Akshay Kumar
Hatya (2004 film)                       Akshay Kumar
Meri Biwi Ka Jawaab Nahin               Akshay Kumar
Police Force: An Inside Story           Akshay Kumar
Andaaz                                  Akshay Kumar
Andaaz                                  Akshay Kumar
Awara Paagal Deewana                    Akshay Kumar
Name: lead, dtype: object

In [33]:
marks={'ram':55,'shyam':60,'seeta':70,'geeta':45}
marks_series=pd.Series(marks,name='Student Result')
print(marks_series)

ram      55
shyam    60
seeta    70
geeta    45
Name: Student Result, dtype: int64

In [34]:
list(marks_series)

[55, 60, 70, 45]

In [35]:
dict(marks_series)

{'ram': 55, 'shyam': 60, 'seeta': 70, 'geeta': 45}

In [36]:
marks_series[1]=111
marks_series

ram       55
shyam    111
seeta     70
geeta     45
Name: Student Result, dtype: int64

In [37]:
100+marks_series

ram      155
shyam    211
seeta    170
geeta    145
Name: Student Result, dtype: int64

In [38]:
marks_series>100

ram      False
shyam     True
seeta    False
geeta    False
Name: Student Result, dtype: bool

In [39]:
# Arithmatic Operations :
import pandas as ps
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,10])
print(a+b)
print("-"*25)
print(a-b)
print("-"*25)
print(a*b)
print("-"*25)
print(a/b)
print("-"*25)
print(a==b)
print("-"*25)
print(a>b)
print("-"*25)
print(a<b)

0     3
1     7
2    11
3    15
4    20
dtype: int64
-------------------------
0    1
1    1
2    1
3    1
4    0
dtype: int64
-------------------------
0      2
1     12
2     30
3     56
4    100
dtype: int64
-------------------------
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64
-------------------------
0    False
1    False
2    False
3    False
4     True
dtype: bool
-------------------------
0     True
1     True
2     True
3     True
4    False
dtype: bool
-------------------------
0    False
1    False
2    False
3    False
4    False
dtype: bool

# 2-D  DataFrame

In [40]:
import pandas as pd
data={'calories':[420,380,390,400],'duration':[50,40,45,48]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45
3       400        48

In [41]:
print(df.loc[0])  # loc used for all type of index
print("")
print(df.loc[1])

calories    420
duration     50
Name: 0, dtype: int64

calories    380
duration     40
Name: 1, dtype: int64

In [42]:
print(df.iloc[0:2:,0])  #iloc[row,column]  iloc used only for integer index

0    420
1    380
Name: calories, dtype: int64

In [43]:
df.loc[[0,2]]

   calories  duration
0       420        50
2       390        45

In [44]:
# Example 1 :
import pandas as pd
data={'Name':['Alice','Bob','Charlie'] , 'Age':[25,30,35] , 'City' : ['New York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [45]:
print(df.loc[0])
print()
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [46]:
print(df.loc[0:2])  # End point include
print()
print(df.iloc[0:2]) # End point not include/exclude

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [47]:
df.loc[(df.Age>26)]

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [48]:
df.loc[(df.Name=='Bob')]

  Name  Age         City
1  Bob   30  Los Angeles

In [49]:
df.loc[(df.Age>26) & (df.City=='Chicago')]

      Name  Age     City
2  Charlie   35  Chicago

In [50]:
# Example 2: 
import pandas as pd
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['r1','r2','r3','r4'])
print(df)
print()
df.loc['r2':'r4','B']=99
print(df)
print()
df.iloc[1:3,0]=0
print(df)
df['C']=[11,22,33,44]
print(df)

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99
    A   B   C
r1  1   5  11
r2  0  99  22
r3  0  99  33
r4  4  99  44

In [51]:
df.loc[df['A']==0,'new_col']='Zero'
df

    A   B   C new_col
r1  1   5  11     NaN
r2  0  99  22    Zero
r3  0  99  33    Zero
r4  4  99  44     NaN

In [52]:
df.loc[len(df)]=[10,11,12,13]
df

     A   B   C new_col
r1   1   5  11     NaN
r2   0  99  22    Zero
r3   0  99  33    Zero
r4   4  99  44     NaN
4   10  11  12      13

In [53]:
# Example 3 :
import pandas as pd
data={'Name':['Alice','Bob','Charlie'] , 'Age':[25,30,35] , 'City' : ['New York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [60]:
df.set_index('Name',drop=False,inplace=True)  # inplace : for update dataframe 
df

            Name  Age         City
Name
Alice      Alice   25     New York
Bob          Bob   30  Los Angeles
Charlie  Charlie   35      Chicago

In [64]:
# Example 4 :
data={'Region':['North','North','South','South'],'City':['NY','LA','Miami','Houston'],'Population':[8.4,3.8,0.4,2.3]}
df=pd.DataFrame(data)
df

  Region     City  Population
0  North       NY         8.4
1  North       LA         3.8
2  South    Miami         0.4
3  South  Houston         2.3

In [65]:
df.set_index(['Region','City'],inplace=True)
df

                Population
Region City
North  NY              8.4
       LA              3.8
South  Miami           0.4
       Houston         2.3

In [68]:
# Example 5 :
data={'Region':['North','North','South','South'],'City':['NY','LA','Miami','Houston'],'Population':[8.4,3.8,0.4,2.3]}
df=pd.DataFrame(data,index=['a','b','c','d'])
df

  Region     City  Population
a  North       NY         8.4
b  North       LA         3.8
c  South    Miami         0.4
d  South  Houston         2.3

In [72]:
df_reset=df.reset_index() 
df_reset

  index Region     City  Population
0     a  North       NY         8.4
1     b  North       LA         3.8
2     c  South    Miami         0.4
3     d  South  Houston         2.3

In [80]:
df_reset=df.reset_index(drop=True) # drop : removing previouse index
df_reset

  Region     City  Population
0  North       NY         8.4
1  North       LA         3.8
2  South    Miami         0.4
3  South  Houston         2.3

In [74]:
df.columns

Index(['Region', 'City', 'Population'], dtype='object')

In [81]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [76]:
df.size

12

In [77]:
df.values

array([['North', 'NY', 8.4],
       ['North', 'LA', 3.8],
       ['South', 'Miami', 0.4],
       ['South', 'Houston', 2.3]], dtype=object)

In [78]:
df.ndim

2

In [79]:
df.shape

(4, 3)