In [7]:
import pandas as pd
data={'Region':['North','North','South','South'],'City':['New York','Los Angles','Miami','Houshi'],'Population':[8.4,3.9,0.4,2.3]}
df=pd.DataFrame(data)
df.sample()  # give random row

  Region    City  Population
3  South  Houshi         2.3

In [11]:
print(df.nunique())

Region        2
City          4
Population    4
dtype: int64

In [18]:
print(df['Region'].unique())

['North' 'South']

In [19]:
print(df['City'].unique())

['New York' 'Los Angles' 'Miami' 'Houshi']

# auto-mpg csv

In [20]:
import pandas as pd
df=pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [25]:
df.info()
df.head(8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii

In [44]:
x=df['horsepower']=='?'
print(df[x].shape)  # (row,column)
df[x].shape[0]  # 6 rows having '?'

(6, 9)

6

In [42]:
df[x].size  # 54=6x9

54

In [45]:
df.describe()  # write this in starting of all csv files

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [49]:
df.isna().sum()  # counting null values

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

 # auto-mpg(change) csv

In [50]:
import pandas as pd
df=pd.read_csv('auto-mpg(change).csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1.0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1.0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1.0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1.0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1.0,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1.0,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2.0,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1.0,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1.0,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1.0,NaN

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           397 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  396 non-null    float64
 6   model year    398 non-null    int64
 7   origin        397 non-null    float64
 8   car name      396 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [53]:
df.isna().sum()

mpg             1
cylinders       0
displacement    1
horsepower      1
weight          0
acceleration    2
model year      0
origin          1
car name        2
dtype: int64

In [63]:
x=df['acceleration'].isnull()
df[x].shape

(2, 9)

# auto-mpg csv

In [93]:
import pandas as pd
df1=pd.read_csv('auto-mpg.csv')
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [79]:
df1.loc[4]

mpg                      17
cylinders                 8
displacement            302
horsepower              140
weight                 3449
acceleration           10.5
model year               70
origin                    1
car name        ford torino
Name: 4, dtype: object

In [80]:
df1.loc[5:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341,10.0,70,1.0,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1.0,NaN
7,14.0,8,440.0,215,4312,8.5,70,1.0,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1.0,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1.0,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1.0,dodge challenger se

In [81]:
df1.iloc[5:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341,10.0,70,1.0,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1.0,NaN
7,14.0,8,440.0,215,4312,8.5,70,1.0,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1.0,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1.0,amc ambassador dpl

In [82]:
df1['car name'].loc[5:10]

5        ford galaxie 500
6                     NaN
7       plymouth fury iii
8        pontiac catalina
9      amc ambassador dpl
10    dodge challenger se
Name: car name, dtype: object

In [83]:
df1.shape

(398, 9)

In [94]:
df1.describe() # objects are not print

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [95]:
import numpy as np
df1.describe(include=[np.number]) #include only number values

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [96]:
df1.describe(exclude=[np.number])

       horsepower    car name
count         398         398
unique         94         305
top           150  ford pinto
freq           22           6

In [97]:
df1.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [100]:
df1.describe(percentiles=[.30,.40,.60])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
30%,18.000000,4.000000,112.000000,2301.000000,14.200000,73.000000,1.000000
40%,20.000000,4.000000,122.000000,2580.600000,14.800000,75.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
60%,25.000000,6.000000,200.000000,3085.200000,16.000000,77.000000,1.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [101]:
df1[['mpg','cylinders']].describe()

              mpg   cylinders
count  398.000000  398.000000
mean    23.514573    5.454774
std      7.815984    1.701004
min      9.000000    3.000000
25%     17.500000    4.000000
50%     23.000000    4.000000
75%     29.000000    8.000000
max     46.600000    8.000000

In [102]:
df1[0:10].describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,10.000000,10.0,10.000000,10.000000,10.000000,10.0,10.0
mean,15.600000,8.0,374.900000,3879.700000,10.300000,70.0,1.0
std,1.577621,0.0,65.722396,432.151735,1.337494,0.0,0.0
min,14.000000,8.0,302.000000,3433.000000,8.500000,70.0,1.0
25%,14.250000,8.0,309.750000,3462.750000,9.250000,70.0,1.0
50%,15.000000,8.0,370.000000,3771.500000,10.250000,70.0,1.0
75%,16.750000,8.0,437.250000,4333.750000,11.375000,70.0,1.0
max,18.000000,8.0,455.000000,4425.000000,12.000000,70.0,1.0

In [103]:
df1.loc[0:10].describe()  # 10 is includes

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,11.000000,11.0,11.000000,11.000000,11.000000,11.0,11.0
mean,15.545455,8.0,375.636364,3850.909091,10.272727,70.0,1.0
std,1.507557,0.0,62.397552,420.948561,1.272078,0.0,0.0
min,14.000000,8.0,302.000000,3433.000000,8.500000,70.0,1.0
25%,14.500000,8.0,312.500000,3476.500000,9.500000,70.0,1.0
50%,15.000000,8.0,383.000000,3693.000000,10.000000,70.0,1.0
75%,16.500000,8.0,434.500000,4326.500000,11.250000,70.0,1.0
max,18.000000,8.0,455.000000,4425.000000,12.000000,70.0,1.0

In [106]:
df1.corr()    # df1.corr(numeric_only=True)  : for updted pandas version

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000